"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import EmotionProvider from "./components/Providers/emotion";
import { AppShell } from "@mantine/core";

import Navigation from "./components/Navigation";
import App from "next/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <EmotionProvider>
          <AppShell navbar={<Navigation />}>{children}</AppShell>
        </EmotionProvider>
      </body>
    </html>
  );
}
