import { FoodItem } from "./types";

const data: FoodItem[] = [
  {
    name: "Chicken Breast",
    brand: "Brookdale",
    calories: 60,
    carbs: 1,
    fat: 1,
    protein: 11,
    serving_size: 56,
    size: 224,
    exp_date: "2025-04-02",
  },
  {
    name: "Chicken Breast",
    brand: "Brookdale",
    calories: 60,
    carbs: 1,
    fat: 1,
    protein: 11,
    serving_size: 56,
    size: 224,
    exp_date: "2025-04-02",
  },
  {
    name: "Chicken Breast",
    brand: "Brookdale",
    calories: 60,
    carbs: 1,
    fat: 1,
    protein: 11,
    serving_size: 56,
    size: 224,
    exp_date: "2025-04-02",
  },
  {
    name: "Raw Honey",
    brand: "Specially Selected",
    calories: 60,
    carbs: 17,
    fat: 0,
    protein: 0,
    serving_size: 21,
    size: 680,
    exp_date: "2023-05-06",
  },
  {
    name: "Corned Beef Hash",
    brand: "Libby's",
    calories: 690,
    carbs: 36,
    fat: 44,
    protein: 37,
    serving_size: 425,
    size: 425,
    exp_date: "2022-05-06",
  },
  {
    name: "Sweet Corn",
    brand: "Happy Harvest",
    calories: 60,
    carbs: 12,
    fat: 1,
    protein: 2,
    serving_size: 125,
    size: 432,
    exp_date: "2023-08-27",
  },
];

export default data;
